/**
 * MGS BOARD GAME COMPANION — STAGES
 *
 * Ogni stage rappresenta una missione della campagna.
 *
 * players:           array dei personaggi attivi nello stage
 * variableActions:   override delle azioni variabili per personaggio
 *                    { "NomePersonaggio": ["id-azione", ...] }
 *                    se assente si usano le defaultVariableActions del personaggio
 *
 * MUSICA DURANTE INTRO:
 *   musicDuringIntro: true  → musica parte durante il video intro
 *   musicIntroDelay:  ms dall'inizio del video (es. 65000 = al secondo 65)
 *   musicIntroVolume: volume 0–100 durante l'intro
 */

const STAGES = [
    {
        id: 1,
        name: "MOLO DI CARICO",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake"],
        description: "Infiltrazione a Shadow Moses Island",
        intro: "video/stage_01_intro.mp4",
        outro: "video/stage_01_outro.mp4",
        events: [
            { id: "A", file: "video/stage_01_A.mp4", stopMusic: false, requiredForOutro: true },
        ],
        disabledActions: ["concentrazione"],
        noConcentrationTokens: true,
        musicIds: ["cavern"],
        musicLabels: ["Molo di carico"],
        enemies: [3],
        enemyEvents: { "A": [{ zone: 0, delta: 1 }] },
        musicDuringIntro: true,
        musicIntroDelay: 65000,
        musicIntroVolume: 10,
        gameOverSounds: ["02", "03", "04", "05"],
        orderCards: 10,
    },
    {
        id: 2,
        name: "ELIPORTO",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake"],
        description: "Attraversamento dell'eliporto",
        intro: "video/stage_02_intro.mp4",
        outro: "video/stage_02_outro.mp4",
        hasCameras: true,
        enemies: [4],
        radioEnemies: [5],
        musicIds: ["arctic-wind"],
        musicLabels: ["Eliporto"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        orderCards: 13,
        events: [
            { id: "A", sound: "audio/sfx/oggetto-preso.wav", requiredForOutro: true },
            { id: "B", sound: "audio/sfx/oggetto-preso.wav" },
        ],
        rewards: {
            always: ["001", "002"],
            conditional: [
                { type: "event", eventId: "B", question: "Hai raccolto l'oggetto B?", equipmentIds: ["003"] },
            ],
        },
    },
    {
        id: 3,
        name: "CELLE DI DETENZIONE",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake", "Meryl"],
        description: "Salvataggio del presidente della DARPA",
        intro: "video/stage_03_intro.mp4",
        outro: "video/stage_03_outro.mp4",
        blockZoneChangeUntilEvent: "B",
        events: [
            { id: "A", file: "video/stage_03_A.mp4", stopMusic: true, requiresZone: 0 },
            { id: "B", file: "video/stage_03_B.mp4", stopMusic: true, requiresEvent: "A", requiresZone: 0 },
            { id: "C", sound: "audio/sfx/oggetto-preso.wav", requiresEvent: "B", requiresZone: 1 },
        ],
        enemies: [3, 3],
        radioEnemies: [3, 3],
        musicIds: ["intruder-4", "intruder-2"],
        musicLabels: ["Celle di detenzione", "Armeria"],
        elevator: "audio/sfx/elevetor.mp3",
        startInAlert: true,
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        orderCards: 13,
        rewards: {
            conditional: [
                {
                    type: "event",
                    eventId: "C",
                    question: "Hai raggiunto il punto C?",
                    equipmentIds: ["005"],
                    elseEquipmentIds: ["004"],
                },
            ],
        },
    },
    {
        id: 4,
        name: "REVOLVER OCELOT",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl"],
        description: "Scontro con Revolver Ocelot",
        intro: "video/stage_04_intro.mp4",
        outro: "video/stage_04_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        variableActions: { "Snake": [], "Meryl": [] },
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["14"],
        bossEnemies: [
            {
                id: "ocelot",
                name: "OCELOT",
                hpByPlayerCount: { 1: 12, 2: 20 },
                attackSound: "audio/sfx/ocelot/attacco-ocelot.wav",
                equipReactions: {
                    "004": { sound: "audio/sfx/ocelot/non ci vedo.wav", delay: 5000 },
                },
                movementSounds: [
                    "audio/sfx/ocelot/movimento1.wav",
                    "audio/sfx/ocelot/movimento2.wav",
                    "audio/sfx/ocelot/movimento3.wav",
                ],
                koTriggersOutro: true,
                hitSequence: {
                    hitSound:  "audio/sfx/colpo-fisico.wav",
                    woundSound: "audio/sfx/ocelot/ocelot-colpito.wav",
                },
                koSound:  "audio/sfx/ocelot/ocelot-ko.wav",
                cards: [
                    { label: "Adoro il profumo della cordite... Per te, però, sarà il profumo della tua morte.",                                              file: "audio/sfx/ocelot/Adoro il profumo della cordite... Per te, però, sarà il profumo della tua morte.wav" },
                    { label: "Meglio se ti sbrighi. Il vecchio non resisterà a lungo.",                                                                       file: "audio/sfx/ocelot/Meglio se ti sbrighi. Il vecchio non resisterà a lungo.wav" },
                    { label: "Nasconderti non ti aiuterà.",                                                                                                   file: "audio/sfx/ocelot/Nasconderti non ti aiuterà.wav" },
                    { label: "Non c'è cosa più bella della sensazione di un lungo proiettile d'argento che scivola in un tamburo ben oliato.",                file: "audio/sfx/ocelot/Non c'è cosa più bella della sensazione di un lungo proiettile d'argento che scivola in un tamburo ben oliato.wav", followUp: "audio/sfx/ocelot/ci siamo sono di nuovo vivo andiamo.wav", followUpAlt: "audio/sfx/ocelot/aspetta un minuto.wav" },
                    { label: "Non vuoi risolvere la questione.",                                                                                              file: "audio/sfx/ocelot/Non vuoi risolvere la questione.wav" },
                    { label: "Io li capisco i proiettili, sai, riesco a farli andare dove voglio.",                                                           file: "audio/sfx/ocelot/io li capisco i proiettili sai riesco a farli andare dove voglio.wav" },
                ],
            },
            { id: "baker",  name: "BAKER",  hp: 3, hitSound: "audio/sfx/ocelot/baker-colpito.wav", koSound: "audio/sfx/ocelot/baker-ko.wav", koTriggersGameOver: true, excludeFrom: ["melee"] },
        ],
        rewards: {
            always: ["006"],
            conditional: [
                {
                    type: "barcode",
                    question: "Hai letto il capitolo Scenario 4 Conclusione?",
                    prompt: "Hai guardato dove ti ha detto Baker? Che equipaggiamento sblocchi?",
                    secret: "031",
                    equipmentIds: ["031"],
                },
            ],
        },
        sfxOnMusicStart: [
            { file: "audio/sfx/ocelot/estrai.wav", delay: 3000 },
            { file: "audio/sfx/baker.wav", delay: 6000, interval: 3000, volume: 0.2 },
        ],
    },
    {
        id: 5,
        name: "IMBOSCATA DEL CARRO ARMATO",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl"],
        description: "Imboscata del carro armato M1",
        intro: "video/stage_05_intro.mp4",
        outro: "video/stage_05_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        variableActions: { "Snake": [], "Meryl": [] },
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        bossEnemies: [
            {
                id: "carro-armato",
                name: "CARRO ARMATO M1",
                hpByPlayerCount: { 1: 20, 2: 40 },
                damageFrom: ["grenade", "mine", "missile"],
                hitSound: "audio/sfx/carroarmato/ferito.wav",
                hitHalfSound: "audio/sfx/carroarmato/ferito+.wav",
                hitHalfVideo: "video/stage_05_boss_ferito.mp4",
                koSound: "audio/sfx/carroarmato/morte.wav",
                attacks: [
                    { name: "CINGOLI",               sound: "audio/sfx/carroarmato/cingoli.wav" },
                    { name: "MITRAGLIATRICE PESANTE", sound: "audio/sfx/carroarmato/mitragliatrice-pesante.wav" },
                    { name: "CANNONE",                sound: "audio/sfx/carroarmato/cannone.wav", hitPopup: true, hitVideo: "video/stage_05_giocatore_ferito.mp4" },
                ],
            },
        ],
        rewards: {
            always: ["007"],
        },
        bossTurnSections: [
            {
                id: "granate",
                label: "GRANATE",
                charges: 2,
                slots: [0, 3],
                actions: [
                    { name: "GETTA LA GRANATA", cost: 1, sound: "audio/sfx/granata.wav", usesCharge: true, attack: true, category: "grenade", itemType: "esplosivo", itemSubtype: "granata", desc: "Tira 2 dadi neri. Colloca 1 granata da questa carta su una casella a un numero di caselle di distanza dalla tua miniatura, in una singola direzione, pari a 1 dei risultati. Poi muovila in un'altra direzione qualsiasi di un numero di caselle pari all'altro risultato. Infliggi 1 danno a ogni miniatura entro 1 casella dalla granata. Se la granata si trova in una casella del Carro Armato, infliggigli i danni seguendo le istruzioni sulla plancia boss. Poi rimuovi dalla mappa la granata. Se la granata sta per muoversi contro un ostacolo o fuori dalla mappa, scartarla senza effetto.", dice: [{ color: "black", count: 2 }] },
                    { name: "CASSA DI GRANATE",  cost: 1, sound: "audio/sfx/oggetto-preso.wav", desc: "Su una icona rifornimento, rifornisci le granate di questa carta.", restoresCharges: true },
                ],
            },
        ],
    },
    {
        id: 6,
        name: "DEPOSITO DELLE TESTATE NUCLEARI",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake", "Meryl"],
        description: "Infiltrazione nel deposito testate nucleari",
        intro: "video/stage_06_intro.mp4",
        outro: "video/stage_06_outro.mp4",
        enemies: [3, 3, 0],
        radioEnemies: [3, 3, 0],
        events: [
            { id: "A", file: "video/stage_06_A.mp4", stopMusic: true, requiredForOutro: true, requiresZone: 2 },
            { id: "B", sound: "audio/sfx/oggetto-preso.wav", requiredForOutro: true, grantEquipment: "E06B", requiresZone: 1 },
            { id: "C", sound: "audio/sfx/oggetto-preso.wav", requiresEvent: "A", requiresZone: 2 },
        ],
        zoneRestrictions: {
            0: { disabledItemTypes: ["arma a distanza", "esplosivo"] },
        },
        musicIds: ["warhead", "intruder-2", "intruder-3"],
        musicLabels: ["Deposito nucleare - L1", "Deposito nucleare - B1", "Deposito nucleare - B2"],
        elevator: "audio/sfx/elevetor.mp3",
        musicDuringIntro: true,
        musicIntroDelay: 61730,
        musicIntroVolume: 20,
        musicIntroStartOffset: 100.29,
        rewards: {
            always: ["009"],
            conditional: [
                { type: "event", eventId: "C", equipmentIds: ["010"] },
            ],
        },
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        orderCards: 18,
    },
    {
        id: 7,
        name: "CYBORG NINJA",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl"],
        description: "Scontro con il Cyborg Ninja",
        intro: "video/stage_07_intro.mp4",
        outro: "video/stage_07_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        variableActions: { "Snake": [], "Meryl": [] },
        musicDuringIntro: true,
        musicIntroDelay: 106240,
        musicIntroVolume: 20,
        bossEnemies: [
            {
                id: "ninja",
                name: "CYBORG NINJA",
                hpByPlayerCount: { 1: 12, 2: 24 },
                damageFrom: ["melee"],
                attackSound: "audio/azioni/ninja/attacco-combo.wav",
                movementSounds: [
                    { file: "audio/azioni/ninja/movimento-furtivo.wav", repeat: 3 },
                    "audio/azioni/ninja/scatto.wav",
                ],
                firstHitVideo: "video/stage_07_ninja_prima_ferita.mp4",
                hitSequence: {
                    hitSound:       "audio/sfx/colpo-fisico.wav",
                    woundSound:     "audio/azioni/ninja/ferito.wav",
                    woundPlusSound: "audio/azioni/ninja/ferito+.wav",
                },
                hitHalfVideo: "video/stage_07_ninja_ferita.mp4",
                damageSounds: [
                    { damage: 2, delay: 1000, sounds: ["audio/sfx/ninja/fammi ancora male.wav", "audio/sfx/ninja/stavo aspettando questo dolore.wav", "audio/sfx/ninja/così così.wav"] },
                ],
                equipReactions: {
                    "003": { sound: "audio/sfx/ninja/ferito-chaff.wav", delay: 5000 },
                },
                koTriggersOutro: true,
                stopMusicOnKo: true,
                koSequence: {
                    sound: "audio/azioni/ninja/concentrazione.wav",
                    volume: 0.25,
                    repeat: 6,
                    overlap: 0.4,       // secondi di anticipo prima della fine per avviare il prossimo
                    fadeOutLast: 1.2,   // secondi prima della fine dell'ultimo play per iniziare il fade out
                    parallelAt: 2,
                    parallelOffset: 0.8, // secondi prima della fine del play #parallelAt per avviare morte
                    parallelSound: "audio/sfx/ninja/morte.wav",
                },
                specialButtons: [
                    {
                        id: "ombra",
                        type: "counter",
                        label: "OMBRA",
                        max: 4,
                        firstVideo:  "video/stage_07_ninja_ombra.mp4",
                        repeatSound: "audio/sfx/ninja/sono qui snake.wav",
                        maxSound:    "audio/sfx/ninja/dove stai guardando.wav",
                    },
                ],
                blockedAttackSounds: [
                    "audio/sfx/ninja/no armi 1.wav",
                    "audio/sfx/ninja/no armi 2.wav",
                    "audio/sfx/ninja/no armi 3.wav",
                ],
                cards: [
                    { label: "Ora possiamo combattere come guerrieri.",        file:  "audio/sfx/ninja/ora possiamo combattere come guerrieri.wav" },
                    { label: "Solo un folle affida la sua vita ad un'arma.",   file:  "audio/sfx/ninja/solo un folle affida la sua vita ad un arma.wav" },
                    { label: "Molto bene, Snake.",                             files: ["audio/sfx/ninja/bella mossa snake.wav", "audio/sfx/ninja/bel colpo snake.wav"] },
                    { label: "Ora sì. Ora ricordo. Quel pugno.",               file:  "audio/sfx/ninja/lo ricordo quel pugno.wav" },
                    { label: "Ricordi, Snake? La sensazione della battaglia. Lo schiantare di ossa e tendini.", file: "audio/sfx/ninja/ossa-tendini.wav" },
                ],
            },
        ],
        rewards: {
            always: ["011"],
        },
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    },
    {
        id: 8,
        name: "PSYCHO MANTIS",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl"],
        description: "Scontro con Psycho Mantis",
        intro: "video/stage_08_intro.mp4",
        mantisIntro: true,
mantisDimostrazione: "video/mantis/mantis_dimostrazione.mp4",
        // Timestamp (secondi dall'inizio di mantis_dimostrazione.mp4) in cui Mantis
        // fa muovere il controller → tremore schermo + volo cursore
        // DA CONFIGURARE dopo aver guardato il video
mantisShakes: [
            { time: 29.50 },
            { time: 30.75 },
            { time: 33.50 },
            { time: 34.50 },
        ],
        outro: "video/stage_08_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        sfxOnMusicStart: [
            { file: "audio/sfx/mantis/blackout.wav", delay: 1500, thenVideo: "video/mantis-video.mp4", thenSfx: "audio/sfx/mantis/mantis-risata.wav" },
        ],
        variableActions: { "Snake": [], "Meryl": [] },
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        bossEnemies: [
            {
                id: "mantis",
                name: "PSYCHO MANTIS",
                hpByPlayerCount: { 1: 15, 2: 30 },
                defense: 12,
                defensePopup: true,
                attackSound: "audio/sfx/mantis/attacco.wav",
                aboveHalfAttackSound: "audio/sfx/mantis/risata.wav",
                equipReactions: {
                    "004": { sound: "audio/sfx/mantis/sono cieco.wav", delay: 5000 },
                },
                movementSounds: ["audio/sfx/mantis/movimento.wav"],
                hitSequence: {
                    hitSound:   "audio/sfx/colpo-fisico.wav",
                    woundSound: "audio/sfx/mantis/ferito.wav",
                },
                hitSound: "audio/sfx/mantis/ferito.wav",
                koSound: "audio/sfx/mantis/morte.wav",
                hitHalfSound: "audio/sfx/mantis/perché non riesco a leggerti nella mente.wav",
                hitExtraSounds: [
                    "audio/sfx/mantis/perché.wav",
                    "audio/sfx/mantis/dove la tua mente.wav",
                ],
                blockedAttackSounds: [
                    "audio/sfx/mantis/è inutile.wav",
                    "audio/sfx/mantis/riesco a vedere i tuoi pensieri.wav",
                ],
                cardsLabel: "Azione",
                cards: [
                    { label: "VIDEO",              file: "audio/sfx/mantis/blackout.wav", thenVideo: "video/mantis-video.mp4", thenSfx: "audio/sfx/mantis/mantis-risata.wav" },
                    { label: "STATUE CADENTI",     file: "audio/sfx/mantis/statue cadenti.wav" },
                    { label: "ARREDAMENTO LETALE", filesAll: ["audio/sfx/mantis/tempesta di mobili.wav", "audio/sfx/mantis/statue cadenti.wav", "audio/sfx/mantis/sedie rotanti.wav", "audio/sfx/mantis/quadri scagliati.wav"] },
                    { label: "TEMPESTA DI MOBILI", file: "audio/sfx/mantis/tempesta di mobili.wav" },
                    { label: "SCARICA PSICHICA",   file: "audio/sfx/mantis/scarica psichica.wav" },
                    { label: "SEDIE ROTANTI",      file: "audio/sfx/mantis/sedie rotanti.wav" },
                    { label: "QUADRI SCAGLIATI",   file: "audio/sfx/mantis/quadri scagliati.wav" },
                ],
            },
        ],
        rewards: {
            always: ["013"],
        },
        gameOverSounds: ["16"],
    },
    {
        id: 9,
        name: "EVASIONE",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Otacon", "Gray Fox"],
        mandatoryPlayers: ["Otacon"],
        description: "Fuga dalla cella di prigionia",
        intro: "video/stage_09_intro.mp4",
        outro: "",
        outroPart1ByPlayer: {
            ketchup:     "video/stage_09_outro_part1_ketchup.mp4",
            "Otacon":    "video/stage_09_outro_part1_otacon.mp4",
            "Gray Fox":  "video/stage_09_outro_part1_ninja.mp4",
        },
        outroPart2: "video/stage_09_outro_part2.mp4",
        musicIds: ["intruder-2", "intruder-4", "cavern"],
        musicLabels: ["Ufficio della sicurezza", "Celle della prigione", "Sala interrogatori"],
        elevator: "audio/sfx/elevetor.mp3",
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        events: [
            { id: "A", sound: "audio/sfx/oggetto-preso.wav", ketchup: true, requiresZone: 1 },
            { id: "liberate-snake", label: "LIBERA SNAKE", requiresZone: 2, requiredForOutro: true, liberate: "snake", sound: "audio/sfx/porta.wav" },
            { id: "liberate-meryl", label: "LIBERA MERYL", requiresZone: 1, requiredForOutro: true, liberate: "meryl", sound: "audio/sfx/porta.wav" },
        ],
        enemies: [3, 3, 3],
        radioEnemies: [3, 3, 3],
        gameOverSounds: ["01"],
        orderCards: { 1: 16, 2: 12 },
        rewards: { always: ["016", "015"] },
        rewardsKetchup: { always: ["016"] },
    },
    {
        id: 10,
        name: "ELICOTTERO DA GUERRA",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Scontro con l'Hind D di Liquid",
        intro: "video/stage_10_intro.mp4",
        outro: "video/stage_10_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        variableActions: { "Snake": [], "Meryl": [], "Otacon": null, "Gray Fox": [] },
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
        rewards: {
            always: ["017"],
        },
        bossEnemies: [
            {
                id: "elicottero",
                name: "ELICOTTERO DA GUERRA",
                hpByPlayerCount: { 1: 12, 2: 24, 3: 30, 4: 35 },
                damageFrom: ["sam"],
                damageSelectorPopup: true,
                attackSounds: ["audio/sfx/elicottero/attacco1.wav", "audio/sfx/elicottero/attacco2.wav"],
                movementSounds: ["audio/sfx/elicottero/elica1.wav", "audio/sfx/elicottero/elica2.wav", "audio/sfx/elicottero/elica3.wav", "audio/sfx/elicottero/elica4.wav", "audio/sfx/elicottero/elica5.wav", "audio/sfx/elicottero/elica6.wav"],
                movementSounds2: ["audio/sfx/elicottero/movimento1.wav", "audio/sfx/elicottero/movimento2.wav"],
            },
        ],
        bossTurnSections: [
            {
                id: "lanciamissili",
                label: "LANCIAMISSILI S.A.M.",
                charges: 3,
                slots: [0, 3],
                actions: [
                    { name: "LANCIA",   cost: 1, sounds: ["audio/sfx/missile-sparato.wav", "audio/sfx/missile-movimento.wav"], usesCharge: true, attack: true, category: "sam", desc: "Scarta 1 proiettile e colloca un missile in una casella adiacente vuota. Poi tira 2 dadi neri e muovi il missile in linea retta, allontanandolo dalla tua miniatura, di un numero di caselle pari al risultato di 1 dei dadi. Poi puoi muoverlo in un'altra direzione qualsiasi allontanandolo di un numero di caselle pari all'altro risultato. Se si muove contro un ostacolo o fuori dalla mappa, scartalo senza effetto. Dopo aver risolto Manovra Evasiva, infliggi all'Elicottero da Guerra un ammontare di danni pari al bersaglio sulla casella in cui si trova il missile. Poi scarta il missile.", dice: [{ color: "black", count: 2 }] },
                    { name: "RICARICA", cost: 1, sound: "audio/sfx/oggetto-preso.wav", desc: "Su una icona rifornimento, rifornisci i proiettili di questa carta.", restoresCharges: true },
                ],
            },
        ],
    },
    {
        id: 11,
        name: "SNIPER WOLF",
        type: "BOSS BATTLE",
        isBoss: true,
        hybridSneaking: { minPlayers: 2 },
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Duello con Sniper Wolf",
        intro: "",
        outro: "",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
    },
    {
        id: 12,
        name: "VULCAN RAVEN",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Scontro con Vulcan Raven",
        intro: "",
        outro: "",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
    },
    {
        id: 13,
        name: "PAL OVERRIDE",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        hasCamerasMinPlayers: 2,
        description: "Sovrascrittura del codice PAL",
        intro: "",
        outro: "",
        musicIds: [],
        musicLabels: [],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
        orderCards: { 1: 20, 2: 16, 3: 12, 4: 10 },
    },
    {
        id: 14,
        name: "METAL GEAR REX",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Battaglia finale contro Metal Gear REX",
        intro: "",
        outro: "",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
    },
];
