/**
 * MGS BOARD GAME COMPANION — STAGES
 *
 * Ogni stage rappresenta una missione della campagna.
 *
 * players:           array dei personaggi attivi nello stage
 * variableActions:   override delle azioni variabili per personaggio
 *                    { "NomePersonaggio": ["id-azione", ...] }
 *                    se assente si usano le defaultVariableActions del personaggio
 *
 * MUSICA DURANTE INTRO:
 *   musicDuringIntro: true  → musica parte durante il video intro
 *   musicIntroDelay:  ms dall'inizio del video (es. 65000 = al secondo 65)
 *   musicIntroVolume: volume 0–100 durante l'intro
 */

const STAGES = [
    {
        id: 1,
        name: "MOLO DI CARICO",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake"],
        description: "Infiltrazione a Shadow Moses Island",
        intro: "video/stage_01_intro.mp4",
        outro: "video/stage_01_outro.mp4",
        events: [
            { id: "A", file: "video/stage_01_A.mp4", stopMusic: false },
        ],
        disabledActions: ["concentrazione"],
        noConcentrationTokens: true,
        musicIds: ["cavern"],
        musicLabels: ["Molo di carico"],
        enemies: [3],
        enemyEvents: { "A": [{ zone: 0, delta: 1 }] },
        musicDuringIntro: true,
        musicIntroDelay: 65000,
        musicIntroVolume: 10,
        gameOverSounds: ["02", "03", "04", "05"],
        orderCards: 10,
    },
    {
        id: 2,
        name: "ELIPORTO",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake"],
        description: "Attraversamento dell'eliporto",
        intro: "video/stage_02_intro.mp4",
        outro: "video/stage_02_outro.mp4",
        hasCameras: true,
        enemies: [4],
        defaultEnemies: [5],
        musicIds: ["arctic-wind"],
        musicLabels: ["Eliporto"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        orderCards: 13,
        rewards: {
            always: ["001", "002"],
            conditional: [
                { question: "Hai completato l'Obiettivo B?", equipmentIds: ["003"] },
            ],
        },
    },
    {
        id: 3,
        name: "CELLE DI DETENZIONE",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake", "Meryl"],
        description: "Salvataggio del presidente della DARPA",
        intro: "video/stage_03_intro.mp4",
        outro: "video/stage_03_outro.mp4",
        events: [
            { id: "A", file: "video/stage_03_A.mp4", stopMusic: true },
            { id: "B", file: "video/stage_03_B.mp4", stopMusic: true },
        ],
        enemies: [3, 3],
        radioEnemies: [3, 3],
        musicIds: ["intruder-4", "intruder-2"],
        musicLabels: ["Celle di detenzione", "Armeria"],
        elevator: "audio/sfx/elevetor.mp3",
        startInAlert: true,
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        orderCards: 13,
        rewards: {
            conditional: [
                {
                    exclusive: true,
                    question: "Come hai completato lo stage?",
                    options: [
                        { label: "Hai sconfitto 12+ guardie nelle Celle di Detenzione", equipmentIds: ["004"] },
                        { label: "Hai raggiunto il punto C e successivamente l'uscita",  equipmentIds: ["005"] },
                    ],
                },
            ],
        },
    },
    {
        id: 4,
        name: "REVOLVER OCELOT",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl"],
        description: "Scontro con Revolver Ocelot",
        intro: "video/stage_04_intro.mp4",
        outro: "video/stage_04_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        variableActions: { "Snake": [], "Meryl": [] },
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["14"],
        bossEnemies: [
            {
                id: "ocelot",
                name: "OCELOT",
                hpByPlayerCount: { 1: 12, 2: 20 },
                attackSound: "audio/sfx/ocelot/attacco-ocelot.wav",
                movementSounds: [
                    "audio/sfx/ocelot/movimento1.wav",
                    "audio/sfx/ocelot/movimento2.wav",
                    "audio/sfx/ocelot/movimento3.wav",
                ],
                koTriggersOutro: true,
                hitSound: "audio/sfx/ocelot/ocelot-colpito.wav",
                koSound:  "audio/sfx/ocelot/ocelot-ko.wav",
                cards: [
                    { label: "Adoro il profumo della cordite... Per te, però, sarà il profumo della tua morte.",                                              file: "audio/sfx/ocelot/Adoro il profumo della cordite... Per te, però, sarà il profumo della tua morte.wav" },
                    { label: "Meglio se ti sbrighi. Il vecchio non resisterà a lungo.",                                                                       file: "audio/sfx/ocelot/Meglio se ti sbrighi. Il vecchio non resisterà a lungo.wav" },
                    { label: "Nasconderti non ti aiuterà.",                                                                                                   file: "audio/sfx/ocelot/Nasconderti non ti aiuterà.wav" },
                    { label: "Non c'è cosa più bella della sensazione di un lungo proiettile d'argento che scivola in un tamburo ben oliato.",                file: "audio/sfx/ocelot/Non c'è cosa più bella della sensazione di un lungo proiettile d'argento che scivola in un tamburo ben oliato.wav", followUp: "audio/sfx/ocelot/ci siamo sono di nuovo vivo andiamo.wav", followUpAlt: "audio/sfx/ocelot/aspetta un minuto.wav" },
                    { label: "Non vuoi risolvere la questione.",                                                                                              file: "audio/sfx/ocelot/Non vuoi risolvere la questione.wav" },
                    { label: "Io li capisco i proiettili, sai, riesco a farli andare dove voglio.",                                                           file: "audio/sfx/ocelot/io li capisco i proiettili sai riesco a farli andare dove voglio.wav" },
                ],
            },
            { id: "baker",  name: "BAKER",  hp: 3, hitSound: "audio/sfx/ocelot/baker-colpito.wav", koSound: "audio/sfx/ocelot/baker-ko.wav", koTriggersGameOver: true, excludeFrom: ["melee"] },
        ],
        rewards: {
            always: ["006"],
            conditional: [
                {
                    type: "barcode",
                    question: "Hai letto il capitolo Scenario 4 Conclusione?",
                    prompt: "Indica cosa c'è scritto sotto il codice a barre della scatola del gioco (3 caratteri):",
                    secret: "031",
                    equipmentIds: ["031"],
                },
            ],
        },
        sfxOnMusicStart: [
            { file: "audio/sfx/ocelot/estrai.wav", delay: 3000 },
            { file: "audio/sfx/baker.wav", delay: 6000, interval: 3000, volume: 0.2 },
        ],
    },
    {
        id: 5,
        name: "IMBOSCATA DEL CARRO ARMATO",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl"],
        description: "Imboscata del carro armato M1",
        intro: "video/stage_05_intro.mp4",
        outro: "video/stage_05_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        variableActions: { "Snake": [], "Meryl": [] },
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        bossEnemies: [
            {
                id: "carro-armato",
                name: "CARRO ARMATO M1",
                hpByPlayerCount: { 1: 20, 2: 40 },
                damageFrom: ["grenade", "mine", "missile"],
                hitSound: "audio/sfx/carroarmato/ferito.wav",
                hitHalfSound: "audio/sfx/carroarmato/ferito+.wav",
                hitHalfVideo: "video/stage_05_boss_ferito.mp4",
                koSound: "audio/sfx/carroarmato/morte.wav",
                attacks: [
                    { name: "CINGOLI",               sound: "audio/sfx/carroarmato/cingoli.wav" },
                    { name: "MITRAGLIATRICE PESANTE", sound: "audio/sfx/carroarmato/mitragliatrice-pesante.wav" },
                    { name: "CANNONE",                sound: "audio/sfx/carroarmato/cannone.wav", hitPopup: true, hitVideo: "video/stage_05_giocatore_ferito.mp4" },
                ],
            },
        ],
        bossTurnSections: [
            {
                id: "granate",
                label: "GRANATE",
                charges: 2,
                slots: [0, 3],
                actions: [
                    { name: "GETTA LA GRANATA", cost: 1, sound: "audio/sfx/granata.wav", usesCharge: true, attack: true, category: "grenade", itemType: "esplosivo", itemSubtype: "granata", desc: "Tira 2 dadi neri. Colloca 1 granata da questa carta su una casella a un numero di caselle di distanza dalla tua miniatura, in una singola direzione, pari a 1 dei risultati. Poi muovila in un'altra direzione qualsiasi di un numero di caselle pari all'altro risultato. Infliggi 1 danno a ogni miniatura entro 1 casella dalla granata. Se la granata si trova in una casella del Carro Armato, infliggigli i danni seguendo le istruzioni sulla plancia boss. Poi rimuovi dalla mappa la granata. Se la granata sta per muoversi contro un ostacolo o fuori dalla mappa, scartarla senza effetto.", dice: [{ color: "black", count: 2 }] },
                    { name: "CASSA DI GRANATE",  cost: 1, sound: "audio/sfx/oggetto-preso.wav", desc: "Su una icona rifornimento, rifornisci le granate di questa carta.", restoresCharges: true },
                ],
            },
        ],
    },
    {
        id: 6,
        name: "DEPOSITO DELLE TESTATE NUCLEARI",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake", "Meryl"],
        description: "Infiltrazione nel deposito testate nucleari",
        intro: "video/stage_06_intro.mp4",
        outro: "video/stage_06_outro.mp4",
        musicIds: ["warhead", "intruder-2", "intruder-3"],
        musicLabels: ["Deposito nucleare - L1", "Deposito nucleare - B1", "Deposito nucleare - B2"],
        elevator: "audio/sfx/elevetor.mp3",
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        orderCards: 18,
    },
    {
        id: 7,
        name: "NINJA CYBORG",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake"],
        description: "Scontro con il Cyborg Ninja",
        intro: "video/stage_07_intro.mp4",
        outro: "video/stage_07_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: true,
        musicIntroDelay: 107000,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
    },
    {
        id: 8,
        name: "PSYCHO MANTIS",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl"],
        description: "Scontro con Psycho Mantis",
        intro: "video/stage_08_intro.mp4",
        mantisIntro: true,
        outro: "video/stage_08_outro.mp4",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["16"],
    },
    {
        id: 9,
        name: "EVASIONE",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Otacon", "Gray Fox"],
        description: "Fuga dalla cella di prigionia",
        intro: "video/stage_09_intro.mp4",
        outro: "",
        musicIds: ["intruder-2", "intruder-4", "cavern"],
        musicLabels: ["Ufficio della sicurezza", "Celle della prigione", "Sala interrogatori"],
        elevator: "audio/sfx/elevetor.mp3",
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: ["02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
        orderCards: { 1: 16, 2: 12 },
    },
    {
        id: 10,
        name: "HELICOPTER GUNSHIP",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Scontro con l'Hind D di Liquid",
        intro: "",
        outro: "",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
    },
    {
        id: 11,
        name: "SNIPER WOLF",
        type: "BOSS BATTLE",
        isBoss: true,
        hybridSneaking: { minPlayers: 2 },
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Duello con Sniper Wolf",
        intro: "",
        outro: "",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
    },
    {
        id: 12,
        name: "VULCAN RAVEN",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Scontro con Vulcan Raven",
        intro: "",
        outro: "",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
    },
    {
        id: 13,
        name: "PAL OVERRIDE",
        type: "SNEAKING MISSION",
        isBoss: false,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        hasCamerasMinPlayers: 2,
        description: "Sovrascrittura del codice PAL",
        intro: "",
        outro: "",
        musicIds: [],
        musicLabels: [],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
        orderCards: { 1: 20, 2: 16, 3: 12, 4: 10 },
    },
    {
        id: 14,
        name: "METAL GEAR REX",
        type: "BOSS BATTLE",
        isBoss: true,
        players: ["Snake", "Meryl", "Otacon", "Gray Fox"],
        description: "Battaglia finale contro Metal Gear REX",
        intro: "",
        outro: "",
        musicIds: ["duel"],
        musicLabels: ["Boss"],
        musicDuringIntro: false,
        musicIntroDelay: 0,
        musicIntroVolume: 20,
        gameOverSounds: null,
    },
];
